### ISSUE TITLE
Terminal Commands used in the exten are powershell based, replace them with generic JS modules.

### ISSUE THREAD

**Issue by UtkarshBhatthere** [UtkarshBhatthere/ESP-Engine#2]
Since the commands used are not OS the extension will not function in Bash based Linux or Mac OS Terminal.

**Comment by binggee9526** [comment]
Hi,I install this extension but it can't work on WSL.
If you want to know which OS is vscode running on,please try this code:
`import os =require('os');`
`let platform = os.platform();`
The 'platform' will be "win32" on windows or "linux" on Linux.

**Comment by UtkarshBhatthere** [comment]
hey, yeah i was intending to develop it that way but then we'll have to manually write scripts for each variant of operating systems. The issue is with the initialize command (since it downloads the template  from ESP's github and set's up stuff. ), rest commands (BUILD, CLEAN, MENUCONFIG etc.) are cmake based (which are platform independent NOTE: Other build-tool chains do not work.) 
-----------------------------------------------------------------------------------------
What I was thinking to be a good solution would be to use Javascript (or Typescript based functions to do the Initialize thing which would work on every OS just fine and we won't need to manually write the script.)
------------------------------------------------------------------------------------------
If you're into Js and wish to contribute then I welcome Pull requests. Otherwise I'll fix this by next week. Meanwhile you can contribute by building up other (Non-Basic commands like FULLCLEAN etc).
------------------------------------------------------------------------------------------

**Comment by binggee9526** [comment]
ok.It sounds a great plan.I will to do what i can.

**Comment by UtkarshBhatthere** [comment]
I saw your merge request. Sorry couldn't keep up with the develpment! I've approved and merged the commit.
