### ISSUE TITLE
Problem with paths

### ISSUE THREAD

**Issue by wnoliveira** [UtkarshBhatthere/ESP-Engine#3]
Hi. I was trying to build from VSCode and the process fail. I have a different path for tools than the standard path for windows, but I think that should work as well.
Here is the problem that I get, including my fail attempt to fix it:
![image](https://user-images.githubusercontent.com/14822231/65064250-6ff12400-d956-11e9-97a5-bdf4c57453ad.png)
Anyone knows how to fix it?

**Comment by UtkarshBhatthere** [comment]
Hey! It appears that you're not using the cmake build system (the last menuconfig command's response), also your environment variable $IDF_PATH is probably not set. You can manually fix this but I'll suggest downloading this - - > https://dl.espressif.com/dl/esp-idf-tools-setup-2.0.exe < - - This sets up the esp-idf, the toolchain, paths, git etc automatically.

**Comment by wnoliveira** [comment]
Hi! Actually I have the esp-idf-tools installed, and the IDF_PATH is correctly set on windows environment. So, I really didn't understand why I am having this problem...

**Comment by UtkarshBhatthere** [comment]
Hey, That's an interesting issue. I think your cmake (or ninja) installation is not added to path. How were you building the project earlier?

**Comment by wnoliveira** [comment]
Hey. I am able to build the project using the ESP-IDF Command Prompt (the one installed with the esp-idf-tools), and this works fine for me.

**Comment by UtkarshBhatthere** [comment]
Oh that's great! I am Sorry i couldn't keep up the development further... I'll resume. Meanwhile if you get across bugs or any feature suggestion please do create issues or feature request!. I am marking this thread closed.
